// Copyright 2025 Scott Friedman
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package software

import (
	"fmt"
	"strings"
)

// LmodConfig holds configuration for Lmod installation and setup.
type LmodConfig struct {
	// InstallPath is where Lmod will be installed (default: /opt/apps)
	InstallPath string
	// Version is the Lmod version to install (default: 8.7.37)
	Version string
	// ModulePath is the root path for modules
	ModulePath string
	// SpackRoot is the Spack installation path
	SpackRoot string
}

// DefaultLmodConfig returns the default Lmod configuration.
func DefaultLmodConfig() *LmodConfig {
	return &LmodConfig{
		InstallPath: "/opt/apps",
		Version:     "8.7.37",
		ModulePath:  "/opt/modules",
		SpackRoot:   "/opt/spack",
	}
}

// LmodInstaller generates scripts for installing and configuring Lmod.
type LmodInstaller struct {
	config *LmodConfig
}

// NewLmodInstaller creates a new Lmod installer.
func NewLmodInstaller(config *LmodConfig) *LmodInstaller {
	if config == nil {
		config = DefaultLmodConfig()
	}
	return &LmodInstaller{config: config}
}

// GenerateInstallScript generates a bash script to install Lmod.
func (l *LmodInstaller) GenerateInstallScript() string {
	var script strings.Builder

	script.WriteString("#!/bin/bash\n")
	script.WriteString("set -e\n\n")
	script.WriteString("# Lmod Installation Script\n")
	script.WriteString("# Generated by pctl\n\n")

	// Install prerequisites
	script.WriteString("echo \"Installing Lmod prerequisites...\"\n")
	script.WriteString("# Remove lua53-devel to avoid conflict with lua-devel\n")
	script.WriteString("yum remove -y lua53-devel || true\n")
	script.WriteString("yum install -y lua lua-devel lua-filesystem lua-posix lua-json \\\n")
	script.WriteString("  tcl tcl-devel\n")
	script.WriteString("# Verify lua-posix is installed\n")
	script.WriteString("lua -e 'require(\"posix\")' 2>/dev/null || {\n")
	script.WriteString("  echo \"ERROR: lua-posix not properly installed\"\n")
	script.WriteString("  yum list installed | grep lua\n")
	script.WriteString("  exit 1\n")
	script.WriteString("}\n")
	script.WriteString("echo \"lua-posix verified successfully\"\n\n")

	// Download and install Lmod
	script.WriteString(fmt.Sprintf("echo \"Installing Lmod %s...\"\n", l.config.Version))
	script.WriteString("cd /tmp\n")
	script.WriteString(fmt.Sprintf("wget -q https://github.com/TACC/Lmod/archive/%s.tar.gz -O lmod-%s.tar.gz\n",
		l.config.Version, l.config.Version))
	script.WriteString(fmt.Sprintf("tar xzf lmod-%s.tar.gz\n", l.config.Version))
	script.WriteString(fmt.Sprintf("cd Lmod-%s\n", l.config.Version))
	script.WriteString(fmt.Sprintf("./configure --prefix=%s\n", l.config.InstallPath))
	script.WriteString("make install\n")
	script.WriteString(fmt.Sprintf("rm -rf /tmp/lmod-%s.tar.gz /tmp/Lmod-%s\n\n", l.config.Version, l.config.Version))

	// Create module directories
	script.WriteString("# Create module directories\n")
	script.WriteString(fmt.Sprintf("mkdir -p %s/Core\n", l.config.ModulePath))
	script.WriteString(fmt.Sprintf("mkdir -p %s/Compiler\n", l.config.ModulePath))
	script.WriteString(fmt.Sprintf("mkdir -p %s/MPI\n\n", l.config.ModulePath))

	// Setup Lmod for all users
	script.WriteString("# Setup Lmod for all users\n")
	script.WriteString("cat > /etc/profile.d/z00_lmod.sh << 'EOF'\n")
	script.WriteString("# Lmod setup\n")
	script.WriteString(fmt.Sprintf("export LMOD_CMD=%s/lmod/lmod/libexec/lmod\n", l.config.InstallPath))
	script.WriteString(fmt.Sprintf("export MODULEPATH_ROOT=%s\n", l.config.ModulePath))
	script.WriteString("\n")
	script.WriteString("# Build MODULEPATH dynamically to support multiple compilers and OS versions\n")
	script.WriteString(fmt.Sprintf("export MODULEPATH=%s/Core", l.config.ModulePath))
	script.WriteString("\n")
	script.WriteString("# Add Spack Core modules if they exist\n")
	script.WriteString(fmt.Sprintf("for core_dir in %s/share/spack/lmod/*/Core; do\n", l.config.SpackRoot))
	script.WriteString("  [ -d \"$core_dir\" ] && export MODULEPATH=\"${MODULEPATH}:${core_dir}\"\n")
	script.WriteString("done\n")
	script.WriteString("\n")
	script.WriteString("# Add all compiler hierarchy paths (gcc, intel, llvm, etc.)\n")
	script.WriteString(fmt.Sprintf("for compiler_version_dir in %s/share/spack/lmod/*/*/*; do\n", l.config.SpackRoot))
	script.WriteString("  # Skip Core directory (already added above)\n")
	script.WriteString("  [ \"$(basename \"$(dirname \"$compiler_version_dir\")\")\" = \"Core\" ] && continue\n")
	script.WriteString("  # Add compiler version hierarchy directories that exist (e.g., gcc/7.3.1, intel/2021.4)\n")
	script.WriteString("  [ -d \"$compiler_version_dir\" ] && export MODULEPATH=\"${MODULEPATH}:${compiler_version_dir}\"\n")
	script.WriteString("done\n")
	script.WriteString("\n")
	script.WriteString("# Initialize Lmod\n")
	script.WriteString("if [ -n \"${BASH_VERSION:-}\" ]; then\n")
	script.WriteString(fmt.Sprintf("  . %s/lmod/lmod/init/bash\n", l.config.InstallPath))
	script.WriteString("elif [ -n \"${ZSH_VERSION:-}\" ]; then\n")
	script.WriteString(fmt.Sprintf("  . %s/lmod/lmod/init/zsh\n", l.config.InstallPath))
	script.WriteString("fi\n")
	script.WriteString("EOF\n\n")

	script.WriteString("echo \"Lmod installation complete!\"\n")
	script.WriteString(fmt.Sprintf("echo \"Modules will be available at: %s\"\n", l.config.ModulePath))

	return script.String()
}

// GenerateSpackIntegrationScript generates a script to integrate Spack with Lmod.
func (l *LmodInstaller) GenerateSpackIntegrationScript() string {
	var script strings.Builder

	script.WriteString("#!/bin/bash\n")
	script.WriteString("set -e\n\n")
	script.WriteString("# Spack-Lmod Integration Script\n")
	script.WriteString("# Generated by pctl\n\n")

	// Source Spack
	script.WriteString(fmt.Sprintf(". %s/share/spack/setup-env.sh\n\n", l.config.SpackRoot))

	// Configure Spack to use Lmod
	script.WriteString("echo \"Configuring Spack to generate Lmod modules...\"\n\n")

	// Create Spack modules configuration
	script.WriteString("mkdir -p ~/.spack\n")
	script.WriteString("cat > ~/.spack/modules.yaml << 'EOF'\n")
	script.WriteString("modules:\n")
	script.WriteString("  default:\n")
	script.WriteString("    enable:\n")
	script.WriteString("      - lmod\n")
	script.WriteString("    lmod:\n")
	script.WriteString("      core_compilers:\n")
	script.WriteString("        - 'gcc@7.3.1'  # System compiler - determines Core vs compiler hierarchy\n")
	script.WriteString("      hierarchy:\n")
	script.WriteString("        - mpi\n")
	script.WriteString("      hash_length: 7\n")
	script.WriteString("      all:\n")
	script.WriteString("        environment:\n")
	script.WriteString("          set:\n")
	script.WriteString("            '{name}_ROOT': '{prefix}'\n")
	script.WriteString("      projections:\n")
	script.WriteString("        all: '{name}/{version}-{hash:7}'\n")
	script.WriteString("        ^mpi: '{name}/{version}-{^mpi.name}-{^mpi.version}-{hash:7}'\n")
	script.WriteString("EOF\n\n")

	// Generate modules from installed packages
	script.WriteString("echo \"Generating Lmod modules for installed Spack packages...\"\n")
	script.WriteString("spack module lmod refresh --delete-tree -y\n\n")

	// No symlinking needed - MODULEPATH now includes Spack's lmod directory
	script.WriteString("echo \"Spack-Lmod integration complete!\"\n")
	script.WriteString("echo \"Modules are available in: %s/share/spack/lmod\"\n")
	script.WriteString("echo \"Use 'module avail' to see available modules\"\n")

	return script.String()
}

// GenerateModuleFile generates a Lmod module file.
func (l *LmodInstaller) GenerateModuleFile(name, version, prefix string, env map[string]string) string {
	var script strings.Builder

	script.WriteString("-- -*- lua -*-\n")
	script.WriteString(fmt.Sprintf("-- Module file for %s %s\n", name, version))
	script.WriteString("-- Generated by pctl\n\n")

	script.WriteString("help([[\n")
	script.WriteString(fmt.Sprintf("This module provides %s version %s\n", name, version))
	script.WriteString("]])\n\n")

	script.WriteString(fmt.Sprintf("whatis(\"Name: %s\")\n", name))
	script.WriteString(fmt.Sprintf("whatis(\"Version: %s\")\n", version))
	script.WriteString(fmt.Sprintf("whatis(\"Description: %s\")\n\n", name))

	// Set environment variables
	if len(env) > 0 {
		script.WriteString("-- Environment variables\n")
		for key, value := range env {
			script.WriteString(fmt.Sprintf("setenv(\"%s\", \"%s\")\n", key, value))
		}
		script.WriteString("\n")
	}

	// Add to PATH
	script.WriteString("-- Update PATH\n")
	script.WriteString(fmt.Sprintf("prepend_path(\"PATH\", \"%s/bin\")\n", prefix))
	script.WriteString(fmt.Sprintf("prepend_path(\"LD_LIBRARY_PATH\", \"%s/lib\")\n", prefix))
	script.WriteString(fmt.Sprintf("prepend_path(\"LD_LIBRARY_PATH\", \"%s/lib64\")\n", prefix))
	script.WriteString(fmt.Sprintf("prepend_path(\"MANPATH\", \"%s/share/man\")\n", prefix))
	script.WriteString(fmt.Sprintf("prepend_path(\"PKG_CONFIG_PATH\", \"%s/lib/pkgconfig\")\n\n", prefix))

	return script.String()
}
